### PR TITLE
[Contrib] Systemd unit files to ease daily CASSH SIGN routine

### PR DESCRIPTION
**Pull request by xakraz**
Requirements:
* Use SystemD
* Install `zenity` for GUI prompt

screenshot_20180911_122815

screenshot_20180911_122837

### CODE REVIEW

**Comment by nbeguier** [comment]
Is there no prerequisites ?

**Comment by xakraz** [comment]
I think it is mentioned in the README file.
But still, it is "contrib", user don't HAVE TO use it, but they can ;)

**Comment by xakraz** [comment]
Is there any blocker that prevent this PR to be merged ?

**Review by nbeguier — DISMISSED** [review]

**Comment by xakraz** [comment]
Arf, rebase dissmissed your approval @nbeguier :(

**Comment by nbeguier** [comment]
No problem, I review it straight away !

**Review by nbeguier — APPROVED** [review]

**Pull request merged**
